### ISSUE TITLE
I can't seem to find the JAR file...

### ISSUE THREAD

**Issue by SynthWeaver** [zeobviouslyfakeacc/ModLoaderInstaller#10]
Am I blind?

**Comment by rogermb** [comment]
You can find the executable JAR file on the [releases page](https://github.com/zeobviouslyfakeacc/ModLoaderInstaller/releases) :smile:

**Comment by zeobviouslyfakeacc** [comment]
You can find the executable JAR file on the [releases page](https://github.com/zeobviouslyfakeacc/ModLoaderInstaller/releases) 😄

**Comment by SynthWeaver** [comment]
Ugh, how stupid of me. Thanks, I am quite new to GitHub.
I don't want to have the same struggle again when I want to download something from GitHub. Could you tell me how I can find the a releases page in a repository?

**Comment by zeobviouslyfakeacc** [comment]
Yeah, GitHub's site design is unintuitive at best...
Here's the release page on the Desktop website: (I don't think they even show that link on mobile...)

![image](https://user-images.githubusercontent.com/29780741/38138351-be81278c-342a-11e8-9da7-02fd29852628.png)

**Comment by SynthWeaver** [comment]
Thank you very much :)
