### ISSUE TITLE
Cannot patch - File status: Invalid

### ISSUE THREAD

**Issue by joelthedangerous** [zeobviouslyfakeacc/ModLoaderInstaller#15]
I just downloaded The Long Dark through steam, i have launched it once, and then i downloaded the TLD Mod Loader Installer. When i select the "tld.exe" i cannot click "patch" because the file status says "Invalid".

Im guessing the patch of TLD is so knew that the TLD mod loader doesnt support it yet. Am i right?

**Comment by zeobviouslyfakeacc** [comment]
Correct. I've been working until a few minutes ago to get a beta version out, which you can find on the [modding discord server](https://discord.gg/kuRa66d) for now.

But please note that this beta version of the mod loader probably won't help you much, as lots of mods (especially libraries used by most other mods) are currently broken. Releasing the mod loader at this point in time would just cause lots of frustration in the form of missing mod features and broken save files.

I'm planning to do a proper release of the mod loader once most mod authors have had some time to catch up and fix their mods / libraries or ensure that they're still working correctly.

**Comment by joelthedangerous** [comment]
Thanks, i just want to install this mod: https://github.com/MikeyPdog/TLD-MouseMod and nothing else. Hopefully it works.

**Comment by joelthedangerous** [comment]
I can confirm that this version works with the mouse mod.
It did not corrupt my save either, but i am only like one minute into the game.

Thanks for your work.

**Comment by zeobviouslyfakeacc** [comment]
Yeah, this definitely shouldn't mess with your save files 😄 
You're welcome! I'm glad to hear it's working! 🎉

**Comment by Augustrae** [comment]
Checking on progress for a Mod Loader update as well.

**Comment by RafaelNET** [comment]
TLD in new version: 1.41
Please, update your great mod!

**Comment by zeobviouslyfakeacc** [comment]
Hi @Augustrae and @RafaelNET! I'll try to get the updated mod loader out by Friday.

I've been super busy in the last few days, so I haven't had much time to work on this. Moreover, even if you had the mod loader, most mods currently don't work with v1.41, as many mods and mod libraries (like ModSettings or the AssetLoader) still need to be updated – the update didn't just ship with a new version of Unity, but it also contains lots of game code changes. We're also doing some work behind the scenes by updating our patching library and by adding mechanisms to make it less likely that users install outdated mods.

Sorry about the longer-than-usual delay. This update was released on a really inopportune weekday in an especially busy week. But if all goes to plan, we should be back up and running soon™️ 😄

**Comment by Augustrae** [comment]
@zeobviouslyfakeacc 

No problem at all. Thanks so much for what you do for TLD community. Your beta loader worked for me and a few mods are working at this point, so I am happy.

**Comment by zeobviouslyfakeacc** [comment]
Done! [Version 1.4](https://github.com/zeobviouslyfakeacc/ModLoaderInstaller/releases/tag/v1.4) has been released 🎉
