### ISSUE TITLE
No longer working with v1.48.1 47676

### ISSUE THREAD

**Issue by qrisjin** [zeobviouslyfakeacc/ModLoaderInstaller#17]
Can no long patch latest version of game (1.48.1 47676).

**Comment by zeobviouslyfakeacc** [comment]
Indeed. An update will follow "Soon™️" :)

**Comment by zeobviouslyfakeacc** [comment]
https://github.com/zeobviouslyfakeacc/ModLoaderInstaller/releases/tag/v1.5
