### ISSUE TITLE
rewired_core.dll

### ISSUE THREAD

**Issue by mmempin26** [zeobviouslyfakeacc/ModLoaderInstaller#18]
Running on MacOs & going through the folder, I do not have the file rewire_core.dll built into the game. I have already verifed my steam folder & it says everything is checked out. Wondering how and where I can get the file?

**Comment by zeobviouslyfakeacc** [comment]
(I think we already discussed this on discord)

It seems that unlike on Windows and Linux, Hinterland did not revert to using the (moddable) Mono backend on Mac. In other words, v1.48 and v1.49 are not moddable on Mac, and v1.47 will likely remain the last moddable version on that operating system.

I'll keep this issue open for visibility and for the case that Hinterland do decide to release another Mono build on Mac.

**Comment by mmempin26** [comment]
Yes, we already discussed this on discord & thank you for your replies. Hopefully, in the future, there will be another way to mod Long Dark again but in the meantime, thanks for the mods!
