### ISSUE TITLE
no main class

### ISSUE THREAD

**Issue by jttoo** [zeobviouslyfakeacc/ModLoaderInstaller#2]
Java Virtual Machine Launcher:
could not find main class:
me.zeobviouslyfakeacc.modloaderinstaller.Main. Program will exit

**Comment by jttoo** [comment]
nevermind, needed to upgare to ver 8

**Comment by blindgamer** [comment]
I'm having the same issue.  I keep getting that error even though JavaFX is installed properly.  And I have the updated JavaFX.

**Comment by zeobviouslyfakeacc** [comment]
I somehow completely missed this issue. Sorry about that, @blindgamer.

But yeah, the solution remains the same: Make sure that you have the Oracle JRE 8 installed 😃
