### ISSUE TITLE
rewired_core.dll 

### ISSUE THREAD

**Issue by lasoleil** [zeobviouslyfakeacc/ModLoaderInstaller#20]
My the long dark is run on window, version is 1.48 but i don't have "managed" folder and "rewired_core.dll" file
So where can i get those file?

**Comment by zeobviouslyfakeacc** [comment]
v1.48 uses the IL2CPP backend and thus cannot be modded. But due to frequent crashes, Hinterland reverted to using the (moddable) Mono backend in v1.48.1 and v1.49. They do intend to go back to the IL2CPP backend in a future release, though, so it appears like the days of modding are numbered.

**Comment by zeobviouslyfakeacc** [comment]
So yeah, for now [version 1.5](https://github.com/zeobviouslyfakeacc/ModLoaderInstaller/releases/tag/v1.5) of the mod loader should work 😄
