### ISSUE TITLE
"Expected the file "Rewired_Core.dll" but no such file was present."

### ISSUE THREAD

**Issue by ArtyCho250** [zeobviouslyfakeacc/ModLoaderInstaller#27]
Hi, I don't have any file named "managed" in my TLD folder, I'm using Steam on Windows. So, I can't install any mods. What can I do against this issue ?
Any help will be appreciated.

**Comment by zeobviouslyfakeacc** [comment]
Hinterland more or less killed modding, and there's not much we can do.
Please read [this note](https://github.com/zeobviouslyfakeacc/ModLoaderInstaller/releases/tag/il2cpp-note) for more information 🙂
