### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by RafaelNET** [zeobviouslyfakeacc/ModLoaderInstaller#30]
You and FINDarkside could create a complete tutorial for creating new mods, with shortcut keys?

Im a dotNet Programmer, but i've never done mod before

**Comment by zeobviouslyfakeacc** [comment]
This mod loader only works with TLD versions 1.56 and earlier, and is thus pretty much dead (or at least it's dying a slow death). I don't think creating a tutorial for modding based on this mod loader would be a good use of my time given these circumstances.

**Comment by RafaelNET** [comment]
Has Hinterland made any future mod unfeasible?

**Comment by zeobviouslyfakeacc** [comment]
At least using this mod loader, yes. Using different mod loaders, it might be possible.

Hinterland also promised to add support for modding "some time soon", but there has been literally zero public communication on this since then, so... don't hold your breath.
