### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Matrixityy** [zeobviouslyfakeacc/ModLoaderInstaller#33]
I tried locating the path to tld.app but it says i need locate it to 'TheLongDark' thing but i dont have it

**Comment by zeobviouslyfakeacc** [comment]
Hi @Matrixityy

As per the release notes, a substantial The Long Dark update fundamentally broke this mod loader over 2 years ago, and it cannot be fixed. We all moved on to MelonLoader, which unfortunately only works on Windows.
