### ISSUE TITLE
Starting to mod

### ISSUE THREAD

**Issue by felipeds** [zeobviouslyfakeacc/ModLoaderInstaller#5]
Not really sure any other way to contact you.

I am starting to play around with mods on TLD. I made a very simple first mod that doubles the speed in which you learn skills.

can you add it to your modlist?

also not really sure any better way to contact you.

**Comment by zeobviouslyfakeacc** [comment]
Done!

I've added the following "description":
> Hate being stuck at low skill levels? This mod doubles the speed at which the player learns skills!

Let me know if that's alright or if you'd like to create your own description 😄 

Some suggestions:
- Few players will want to build their mods themselves.  
You should probably consider uploading a pre-built DLL to your [releases page](https://github.com/felipeds/Quick-Wittted/releases)
- These annotations
  ```csharp
    [HarmonyPatch(typeof(SkillsManager))]
    [HarmonyPatch("IncrementPointsAndNotify")]
  ```
  could be merged into one:
  ```csharp
    [HarmonyPatch(typeof(SkillsManager), "IncrementPointsAndNotify")]
  ```
- If you only ever return true from a Prefix method, you could let the return type be void:
  ```
    static void Prefix(ref int numPoints)
  ```
  But the result is the same :smile:

By the way, we also have a [discord server](https://discord.gg/VqCUgTJ) dedicated to modding TLD that might be interesting to you :blush:
